In [1]:
import numpy as np
# scale = 1/lambda (rate parameter). Default scale=1.0 is fine unless told otherwise.
arr_4x4 = np.random.exponential(scale=1.0, size=(4, 4))
print(arr_4x4)

[[6.92389463 2.95276448 0.27999179 0.55602876]
 [0.26330056 0.55119547 2.40917351 0.12386545]
 [0.0947689  1.86305766 0.30599495 1.48714412]
 [2.19250356 1.8061499  0.16368894 0.65593159]]
